config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'meetings#index', to: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create

    @meeting = Meeting.new(meeting_params)

    meeting_time = [
      @meeting.start_time_1,
      @meeting.start_time_2,
      @meeting.start_time_3
    ]

    @meeting.meeting_instances.times do |i|
      @meeting = Meeting.new({name: @meeting.name, start_time: meeting_time[i]})
      @meeting.save
    end

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update



    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :start_time_1, :start_time_2, :start_time_3, :meeting_instances)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cal2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/meetings/_form.html.erb
<script type="text/javascript">
  $( document ).ready( function(num){
    init()

    $( '#add-button' ).click( function( e ){
      e.preventDefault()
      num++
      updateNum()
      addEvent()
      toggleButtons()
    })

    $( '#subtract-button' ).click( function( e ){
      e.preventDefault()
      removeEvent()
      num--
      updateNum()
      toggleButtons()
    })

    function init(){
      num = 1
      $( '#meeting_meeting_instances' ).val(num)
      $( '#2, #3' ).hide()
      $( '#subtract-button' ).hide()
    }
    function toggleButtons(){
      switch(num) {
        case 1:
          $( '#add-button' ).show()
          $( '#subtract-button' ).hide()
            break;
        case 3:
          $( '#add-button' ).hide()
          $( '#subtract-button' ).show()
            break;
        default:
          $( '#add-button' ).show()
          $( '#subtract-button' ).show()
      }
    }
    function addEvent(){ $( '#' + num.toString() ).show() }
    function removeEvent(){ $( '#' + num.toString() ).hide() }
    function updateNum(){ $( '#meeting_meeting_instances' ).val(num) }
  })
</script>

<div class="row">

  <%= form_for(meeting) do |f| %>
    <% if meeting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

        <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>



    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <% if !current_page?(controller: 'meetings', action: 'new') %>
      <div class="field" id="1">
        <%= f.label :start_time %>
        <%= f.datetime_select :start_time %>
      </div>
    <% else %>
      <div class="field" id="1">
        <%= f.label :start_time %>
        <%= f.datetime_select :start_time_1 %>
      </div>
    <% end %>






    <div class="field" id="2">
      <%= f.label :start_time_2 %>
      <%= f.datetime_select :start_time_2 %>
    </div>

    <div class="field" id="3">
      <%= f.label :start_time_3 %>
      <%= f.datetime_select :start_time_3 %>
    </div>

    <% if current_page?(controller: 'meetings', action: 'new') %>
      <button id="add-button"><h4>+</h4></button>
      <button id="subtract-button"><h4>-</h4></button>
    <% end %>



    <div class="actions">
      <%= f.submit %>
    </div>

    <div class="hidden-element" >
      <%= f.label :meeting_instances %>
      <%= f.text_field :meeting_instances %>
    </div>
  <% end %>

</div>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Destroy', @meeting, method: :delete %>
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<%= link_to 'New Meeting', new_meeting_path %>



<%= month_calendar events: @meetings do |date, meetings| %>

  <div style="width:44px">
    <span class="day"><%= date.day %></span>
  </div>



  <% meetings.each do |meeting| %>
    <div>
      <%= link_to meeting.name, meeting %>
    </div>
  <% end %>



<% end %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>



<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>